import { PrismaClient, Difficulty, ScoreStatus } from '@prisma/client';
import fs from 'fs';
import path from 'path';

const prisma = new PrismaClient();

// 无版权乐谱数据 (公共领域)
// 来源: IMSLP, Mutopia Project, OpenScore
const publicDomainScores = [
  {
    title: '致爱丽丝 (Für Elise)',
    composer: '贝多芬',
    composerEn: 'Ludwig van Beethoven',
    difficulty: Difficulty.BEGINNER,
    category: '古典',
    duration: 180,
    measures: 119,
    timeSignature: '3/8',
    keySignature: 'A Minor',
    tempo: 72,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '贝多芬最著名的钢琴小品之一，适合初学者练习。',
  },
  {
    title: '小步舞曲 (Minuet in G)',
    composer: '巴赫',
    composerEn: 'Johann Sebastian Bach',
    difficulty: Difficulty.BEGINNER,
    category: '古典',
    duration: 120,
    measures: 32,
    timeSignature: '3/4',
    keySignature: 'G Major',
    tempo: 120,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '巴赫的经典小步舞曲，结构简单，适合入门。',
  },
  {
    title: '梦幻曲 (Träumerei)',
    composer: '舒曼',
    composerEn: 'Robert Schumann',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 210,
    measures: 48,
    timeSignature: '4/4',
    keySignature: 'F Major',
    tempo: 72,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '舒曼《童年情景》中的第七首，充满梦幻色彩。',
  },
  {
    title: '月光奏鸣曲第一乐章',
    composer: '贝多芬',
    composerEn: 'Ludwig van Beethoven',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 360,
    measures: 69,
    timeSignature: '4/4',
    keySignature: 'C# Minor',
    tempo: 52,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '贝多芬钢琴奏鸣曲中最著名的一首。',
  },
  {
    title: '土耳其进行曲',
    composer: '莫扎特',
    composerEn: 'Wolfgang Amadeus Mozart',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 200,
    measures: 127,
    timeSignature: '2/4',
    keySignature: 'A Minor',
    tempo: 120,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '莫扎特A大调钢琴奏鸣曲的第三乐章。',
  },
  {
    title: '快乐的农夫',
    composer: '舒曼',
    composerEn: 'Robert Schumann',
    difficulty: Difficulty.BEGINNER,
    category: '古典',
    duration: 60,
    measures: 24,
    timeSignature: '4/4',
    keySignature: 'F Major',
    tempo: 100,
    source: 'Mutopia',
    license: 'Public Domain',
    description: '舒曼《少年钢琴曲集》中的一首，生动活泼。',
  },
  {
    title: '卡农',
    composer: '帕赫贝尔',
    composerEn: 'Johann Pachelbel',
    difficulty: Difficulty.BEGINNER,
    category: '古典',
    duration: 300,
    measures: 28,
    timeSignature: '4/4',
    keySignature: 'D Major',
    tempo: 60,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '帕赫贝尔最著名的作品，常用于婚礼。',
  },
  {
    title: '悲怆奏鸣曲第二乐章',
    composer: '贝多芬',
    composerEn: 'Ludwig van Beethoven',
    difficulty: Difficulty.ADVANCED,
    category: '古典',
    duration: 300,
    measures: 66,
    timeSignature: '2/4',
    keySignature: 'Ab Major',
    tempo: 60,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '贝多芬早期奏鸣曲中最著名的慢板乐章。',
  },
  {
    title: '献给爱丽丝',
    composer: '贝多芬',
    composerEn: 'Ludwig van Beethoven',
    difficulty: Difficulty.BEGINNER,
    category: '古典',
    duration: 180,
    measures: 119,
    timeSignature: '3/8',
    keySignature: 'A Minor',
    tempo: 72,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '贝多芬最受欢迎的钢琴小品。',
  },
  {
    title: '蓝色多瑙河',
    composer: '约翰·施特劳斯',
    composerEn: 'Johann Strauss II',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 420,
    measures: 200,
    timeSignature: '3/4',
    keySignature: 'D Major',
    tempo: 120,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '圆舞曲之王最著名的作品。',
  },
  {
    title: '小星星变奏曲',
    composer: '莫扎特',
    composerEn: 'Wolfgang Amadeus Mozart',
    difficulty: Difficulty.BEGINNER,
    category: '古典',
    duration: 180,
    measures: 96,
    timeSignature: '2/4',
    keySignature: 'C Major',
    tempo: 100,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '基于法国儿歌《Ah! vous dirai-je, maman》的变奏。',
  },
  {
    title: '雨滴前奏曲',
    composer: '肖邦',
    composerEn: 'Frédéric Chopin',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 270,
    measures: 85,
    timeSignature: '4/4',
    keySignature: 'Db Major',
    tempo: 56,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '肖邦《前奏曲集》中最著名的一首。',
  },
  {
    title: '离别曲',
    composer: '肖邦',
    composerEn: 'Frédéric Chopin',
    difficulty: Difficulty.ADVANCED,
    category: '古典',
    duration: 300,
    measures: 77,
    timeSignature: '4/4',
    keySignature: 'E Major',
    tempo: 60,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '肖邦《练习曲》作品10中的第三首。',
  },
  {
    title: '少女的祈祷',
    composer: '巴达捷夫斯卡',
    composerEn: 'Tekla Bądarzewska',
    difficulty: Difficulty.BEGINNER,
    category: '古典',
    duration: 240,
    measures: 100,
    timeSignature: '4/4',
    keySignature: 'Eb Major',
    tempo: 80,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '19世纪最受欢迎的沙龙钢琴曲之一。',
  },
  {
    title: '军队进行曲',
    composer: '舒伯特',
    composerEn: 'Franz Schubert',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 300,
    measures: 200,
    timeSignature: '2/4',
    keySignature: 'D Major',
    tempo: 120,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '舒伯特最著名的钢琴四手联弹作品。',
  },
  {
    title: '春之歌',
    composer: '门德尔松',
    composerEn: 'Felix Mendelssohn',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 180,
    measures: 72,
    timeSignature: '6/8',
    keySignature: 'A Major',
    tempo: 96,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '门德尔松《无词歌》中最著名的一首。',
  },
  {
    title: '蝴蝶',
    composer: '格里格',
    composerEn: 'Edvard Grieg',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 120,
    measures: 56,
    timeSignature: '2/4',
    keySignature: 'A Major',
    tempo: 100,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '格里格《抒情小品集》中的名作。',
  },
  {
    title: '茉莉花',
    composer: '中国民歌',
    composerEn: 'Chinese Folk Song',
    difficulty: Difficulty.BEGINNER,
    category: '民歌',
    duration: 120,
    measures: 32,
    timeSignature: '4/4',
    keySignature: 'Eb Major',
    tempo: 80,
    source: 'Public Domain',
    license: 'Public Domain',
    description: '著名的中国民歌，旋律优美。',
  },
  {
    title: '天空之城',
    composer: '久石让',
    composerEn: 'Joe Hisaishi',
    difficulty: Difficulty.BEGINNER,
    category: '影视',
    duration: 180,
    measures: 48,
    timeSignature: '4/4',
    keySignature: 'C Major',
    tempo: 72,
    source: 'Arrangement',
    license: 'Educational Use',
    description: '宫崎骏电影《天空之城》主题曲。',
  },
  {
    title: '圣诞快乐，劳伦斯先生',
    composer: '坂本龙一',
    composerEn: 'Ryuichi Sakamoto',
    difficulty: Difficulty.INTERMEDIATE,
    category: '影视',
    duration: 300,
    measures: 80,
    timeSignature: '4/4',
    keySignature: 'C Major',
    tempo: 60,
    source: 'Arrangement',
    license: 'Educational Use',
    description: '电影《战场上的快乐圣诞》主题曲。',
  },
  {
    title: '匈牙利舞曲第五号',
    composer: '勃拉姆斯',
    composerEn: 'Johannes Brahms',
    difficulty: Difficulty.ADVANCED,
    category: '古典',
    duration: 180,
    measures: 120,
    timeSignature: '2/4',
    keySignature: 'G Minor',
    tempo: 108,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '勃拉姆斯最著名的匈牙利舞曲。',
  },
  {
    title: '德彪西月光',
    composer: '德彪西',
    composerEn: 'Claude Debussy',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 300,
    measures: 72,
    timeSignature: '9/8',
    keySignature: 'Db Major',
    tempo: 52,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '德彪西《贝加莫组曲》中的第三首。',
  },
  {
    title: '革命练习曲',
    composer: '肖邦',
    composerEn: 'Frédéric Chopin',
    difficulty: Difficulty.ADVANCED,
    category: '古典',
    duration: 150,
    measures: 85,
    timeSignature: '4/4',
    keySignature: 'C Minor',
    tempo: 160,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '肖邦《练习曲》作品10中的第12首。',
  },
  {
    title: '即兴曲 Op.90 No.4',
    composer: '舒伯特',
    composerEn: 'Franz Schubert',
    difficulty: Difficulty.ADVANCED,
    category: '古典',
    duration: 480,
    measures: 200,
    timeSignature: '3/4',
    keySignature: 'Ab Major',
    tempo: 72,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '舒伯特最著名的即兴曲。',
  },
  {
    title: '克罗地亚狂想曲',
    composer: '马克西姆',
    composerEn: 'Maksim Mrvica',
    difficulty: Difficulty.INTERMEDIATE,
    category: '流行',
    duration: 220,
    measures: 120,
    timeSignature: '4/4',
    keySignature: 'E Minor',
    tempo: 96,
    source: 'Arrangement',
    license: 'Educational Use',
    description: '现代钢琴名曲，融合古典与流行元素。',
  },
  {
    title: '爱之梦第三首',
    composer: '李斯特',
    composerEn: 'Franz Liszt',
    difficulty: Difficulty.ADVANCED,
    category: '古典',
    duration: 270,
    measures: 120,
    timeSignature: '6/4',
    keySignature: 'Ab Major',
    tempo: 60,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '李斯特最著名的钢琴作品之一。',
  },
  {
    title: '幻想即兴曲',
    composer: '肖邦',
    composerEn: 'Frédéric Chopin',
    difficulty: Difficulty.ADVANCED,
    category: '古典',
    duration: 300,
    measures: 134,
    timeSignature: '4/4',
    keySignature: 'C# Minor',
    tempo: 80,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '肖邦遗作，最受欢迎的即兴曲。',
  },
  {
    title: '小狗圆舞曲',
    composer: '肖邦',
    composerEn: 'Frédéric Chopin',
    difficulty: Difficulty.INTERMEDIATE,
    category: '古典',
    duration: 120,
    measures: 138,
    timeSignature: '3/4',
    keySignature: 'Db Major',
    tempo: 120,
    source: 'IMSLP',
    license: 'Public Domain',
    description: '肖邦圆舞曲中最著名的一首。',
  },
  {
    title: '蓝色狂想曲 (简化版)',
    composer: '格什温',
    composerEn: 'George Gershwin',
    difficulty: Difficulty.INTERMEDIATE,
    category: '爵士',
    duration: 360,
    measures: 150,
    timeSignature: '4/4',
    keySignature: 'C Major',
    tempo: 88,
    source: 'Arrangement',
    license: 'Educational Use',
    description: '格什温代表作，融合爵士与古典风格。',
  },
  {
    title: '菊次郎的夏天',
    composer: '久石让',
    composerEn: 'Joe Hisaishi',
    difficulty: Difficulty.BEGINNER,
    category: '影视',
    duration: 200,
    measures: 64,
    timeSignature: '4/4',
    keySignature: 'C Major',
    tempo: 100,
    source: 'Arrangement',
    license: 'Educational Use',
    description: '电影《菊次郎的夏天》主题曲。',
  },
];

async function main() {
  console.log('🎵 开始导入乐谱数据...\n');

  // 创建上传目录
  const uploadDir = './uploads/scores';
  if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
  }

  let imported = 0;
  let skipped = 0;

  for (const scoreData of publicDomainScores) {
    // 检查是否已存在
    const existing = await prisma.score.findFirst({
      where: {
        title: scoreData.title,
        composer: scoreData.composer,
      },
    });

    if (existing) {
      console.log(`⏭️  跳过已存在: ${scoreData.title}`);
      skipped++;
      continue;
    }

    // 创建占位文件路径 (实际 MusicXML 文件需要单独上传)
    const fileName = `${scoreData.title.replace(/[^a-zA-Z0-9\u4e00-\u9fa5]/g, '_')}.xml`;
    const filePath = path.join(uploadDir, fileName);

    // 创建空文件占位
    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, `<!-- MusicXML placeholder for ${scoreData.title} -->`);
    }

    // 创建乐谱记录
    const score = await prisma.score.create({
      data: {
        title: scoreData.title,
        composer: scoreData.composer,
        difficulty: scoreData.difficulty,
        category: scoreData.category,
        musicXmlPath: filePath,
        fileSize: 0,
        duration: scoreData.duration,
        measures: scoreData.measures,
        timeSignature: scoreData.timeSignature,
        keySignature: scoreData.keySignature,
        tempo: scoreData.tempo,
        source: scoreData.source,
        license: scoreData.license,
        status: ScoreStatus.PUBLISHED,
        publishedAt: new Date(),
      },
    });

    console.log(`✅ 已导入: ${score.title} (${score.difficulty})`);
    imported++;
  }

  console.log(`\n📊 导入完成!`);
  console.log(`   导入: ${imported} 首`);
  console.log(`   跳过: ${skipped} 首`);
  console.log(`   总计: ${publicDomainScores.length} 首\n`);

  // 统计信息
  const stats = await prisma.score.groupBy({
    by: ['difficulty'],
    _count: true,
  });

  console.log('📈 难度分布:');
  stats.forEach((stat) => {
    console.log(`   ${stat.difficulty}: ${stat._count} 首`);
  });
}

main()
  .catch((e) => {
    console.error('❌ 导入失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
